### ISSUE TITLE
can't build macOS swift api

### ISSUE THREAD

**Issue by samirsd** [ipfs/swift-ipfs-api#6]
when I try to build for macOS I get:

after running carthage update 

running macOS Sierra 10.12.6

*** Building scheme "SwiftGMP" in SwiftGMP.xcodeproj
Failed to write to /Users/me/Carthage/Checkouts/SwiftGMP/Carthage/Build/Mac/SwiftGMP.framework: Error Domain=NSCocoaErrorDomain Code=260 "The file “SwiftGMP.framework” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/SwiftGMP/v0.4.8/Build/Intermediates.noindex/ArchiveIntermediates/SwiftGMP/BuildProductsPath/Release-iphoneos/SwiftGMP.framework, NSFilePath=/Users/me/Library/Caches/org.carthage.CarthageKit/DerivedData/9.2_9C40b/SwiftGMP/v0.4.8/Build/Intermediates.noindex/ArchiveIntermediates/SwiftGMP/BuildProductsPath/Release-iphoneos/SwiftGMP.framework, NSUnderlyingError=0x7fc3f9452180 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}

**Comment by NeoTeo** [comment]
I have just fixed an issue caused by a deep dependency Swift language deprecation error. This might well have been caused by that. I have now checked the whole dependency chain and confirmed everything works. Please have a look at my [Mac ipfs project](https://github.com/NeoTeo/IpfsMacAppExample) for a working example.

**Comment by samirsd** [comment]
got it working now thanks!
