### ISSUE TITLE
No such module 'SwiftIpfsApi'

### ISSUE THREAD

**Issue by mrn10001** [ipfs/swift-ipfs-api#7]
After adding the frameworks from Carthage/Build/Mac, the module is not recognized when I try to import it to a file.  I have tried in both Xcode 9.2 and Xcode 8.0.

**Comment by NeoTeo** [comment]
I have just fixed an issue caused by a deep dependency Swift language deprecation error. This does not necessarily sound like it's related but I have just gone through the whole chain to check everything works and it does. Please check my [example Mac project](https://github.com/NeoTeo/IpfsMacAppExample) that uses the swift-ipfs-api.

**Comment by mrn10001** [comment]
Was this fixed for the iOS build as well?

**Comment by dominic-healid** [comment]
Any update?

What are the frameworks to be added on the project after running carthage?
